### ISSUE TITLE
Styles of the components get overwritten 

### ISSUE THREAD

**Issue by DewaldOosthuizen** [skdharmarajan/snackbar#5]
Hi,

Looks like the styles of your components get overridden by styles in the main styles.css and/or other style sheets specified. Is there a way you can isolate your styles to your components and ensure they are applied and not styles from outside the components?

Or provide a way to specify a style sheet specifically for these components? 

Perhaps applying specific style names to your styles e.g [.header -> .snackbar-header, .sub-header -> .snackbar-sub-header]

![screenshot_20181130_125015](https://user-images.githubusercontent.com/13827729/49284876-89e07980-f49e-11e8-8f5e-25e04a8ba927.png)

**Comment by skdharmarajan** [comment]
Hi,
Thanks for creating the issue. I am working on it to resolve the issue. 
ETA :- 4-6 hrs.

**Comment by skdharmarajan** [comment]
Issue Resolved. Please get latest 1.7.8 Version.

**Comment by skdharmarajan** [comment]
Please get latest of 1.7.9.
